name: sarvalanche
channels:
  - conda-forge
dependencies:
  - pyproj
  - asf_search
  - py3dep
  - rioxarray
  - ipykernel
  - tqdm
  - matplotlib
  - pytest
  - pytest-mock
  - dask
  - earthaccess
  - pygeohydro
  - bottleneck
  - scikit-image
  - pytorch
  - timm