name: pydensecrf
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - icu=78.2=h38cb7af_0
  - libffi=3.5.2=hcf2aa1b_0
  - liblzma=5.8.2=h8088a28_0
  - liblzma-devel=5.8.2=h8088a28_0
  - libsqlite=3.51.2=h1ae2325_0
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.5=h5e97a16_3
  - openssl=3.6.1=hd24854e_1
  - pip=24.3.1=pyh8b19718_0
  - python=3.8.20=h7d35d02_2_cpython
  - readline=8.3=h46df422_0
  - setuptools=75.3.0=pyhd8ed1ab_0
  - tk=8.6.13=h010d191_3
  - wheel=0.45.1=pyhd8ed1ab_0
  - xz=5.8.2=hd0f0c4f_0
  - xz-gpl-tools=5.8.2=hd0f0c4f_0
  - xz-tools=5.8.2=h8088a28_0
  - pip:
      - cython==3.2.4
      - numpy==1.24.4
      - pydensecrf==1.0
prefix: /Users/zmhoppinen/miniforge3/envs/py38
